### ISSUE TITLE
Error when running a custom VNTR analysis

### ISSUE THREAD

**Issue by dbayles** [WGS-TB/PythonPRINCE#14]
I'm running the bioconda release of prince (v 2.2).  I went through the process of building a new model for a VNTR analysis on a bacterium (not M. tuberculosis).  Building the new boost output training file using simulated reads worked fine and the output file was similar in structure to the examples included with prince.  When I attempt to run a test genome against the new model, I'm getting an error that I've been unable to fix.  Note: I'm not a python programmer.  Here's an example of the command I'm executing:
$ prince -tf samples.txt -to output.txt -bo new_training_output.txt -p new_primers.json -tmp new_templates.fasta

The "samples.txt" file contains the naming prefix for the real reads I want to analyze.  In the current case this is "203_100x_R".  The "new_training_output.txt" file contains my boost output created from simulated reads with genomes where the copy number of the VNTR was altered to known numbers from 1 to 15.  The "new_primers.json" contains my flanking primers, and "new_templates.fasta" contains the repeat.  Currently, I'm only analyzing a single VNTR locus and one particular tandem repeat.  When I execute the code, I receive the following terminal output and error:
Running 203_100x_R
[1213]
[0]
[1213.0]

Traceback (most recent call last):
  File "/Data/projects/prince/bin/prince", line 64, in <module>
    main()
  File "/Data/projects/prince/bin/prince", line 61, in main
    test_target(prince_options, template_obj, primers)
  File "/Data/projects/prince/lib/python2.7/site-packages/prince/query_sample.py", line 21, in test_target
    equations = get_equations(data)
  File "/Data/projects/prince/lib/python2.7/site-packages/prince/predict.py", line 23, in get_equations
    slope, intercept, r_value, p_value, std_err = stats.linregress(X,Y)
  File "/Data/projects/prince/lib/python2.7/site-packages/scipy/stats/_stats_mstats_common.py", line 95, in linregress
    raise ValueError("Inputs must not be empty.")
ValueError: Inputs must not be empty.

If I execute the same samples.txt file using the default M. tb model, templates, and primers, the program runs to completion, so I know the input sample reads files are able to be analyzed.  Any ideas on how to resolve this particular error message?

**Comment by Leonardini** [comment]
I am requesting Julius, one of the developers and the current maintainer of PRINCE, to address this issue.

**Comment by dbayles** [comment]
I appreciate that.

**Comment by JuliusBooth** [comment]
Hi. I have fixed the issue and have published a new release (v2.3). It should be published to bioconda quite soon.

It should work with python2.7 but I'd recommend you use python3.6 with Prince if possible.

**Comment by dbayles** [comment]
Thank you Julius.  I'll watch for the release and update my installation.
