### ISSUE TITLE
`prince` in `bin` does not work.

### ISSUE THREAD

**Issue by realseanla** [WGS-TB/PythonPRINCE#6]
When I run `bin/prince` in the main directory, I get the following error:
```bash
[seanla@sabin PythonPRINCE]$ bin/prince
Traceback (most recent call last):
  File "bin/prince", line 8, in <module>
    from prince.kmer_generator import kmer_generator
ImportError: No module named kmer_generator
```
`prince` probably needs to be in the top-level directory.

**Comment by dfornika** [comment]
Hi Sean,

We're working on packaging prince for distribution. Sorry that the installation instructions aren't quite up-to-date. I'd recommend creating a [conda](https://conda.io/miniconda.html) environment and installing prince into that. From the top-level of the repository, run:

```
conda create -n prince python=3
source activate prince
pip install -r requirements.txt
pip intall -e .
```

Then `prince` should be available on your `PATH` within the conda environment.

**Comment by realseanla** [comment]
Thanks!
